name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: "To know whether it's a mod compatibility issue, please remove all other mods and keep only Immersive Portals and Fabric API, backup your world, and then test again whether the issue occurs. Thanks for cooperation. \nIf Immersive Portals mod makes other mod's functionality break, you don't need to test it, simply select Yes below."
  - type: dropdown
    id: only_immptl
    attributes:
      label: Is it a mod compatibility issue?
      options:
        - "Select One"
        - "Yes"
        - "No"
    validations:
      required: true
  - type: dropdown
    id: mc_version
    attributes:
      label: Minecraft version
      options:
        - "Select One"
        - "1.19.4"
        - "1.19.3"
        - "1.19.2"
        - "1.19"
        - "1.18.x"
        - "1.17.x"
        - "Other"
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Describe the issue. Drag the log and crash report to here. The log is `latest.log` in `logs` folder in the game directory. The log provides useful information (including the mod list) for debugging the issue.
      value: "Describe the issue."
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### The maintainer may ask questions for clarifying this issue. Simply submitting a vague issue without replying will get ignored."
