name: Mod Compatibility Issue Report
description: File a mod-compatibility issue report
body:
  - type: dropdown
    id: mc_version
    attributes:
      label: Minecraft version
      options:
        - "Select One"
        - "1.20.1"
        - "1.20"
        - "1.19.4"
        - "1.19.3"
        - "1.19.2"
        - "1.19"
        - "1.18.x"
        - "1.17.x"
        - "Other"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "
        ### Please find exactly which mod is incompatible. Simply providing a mod list with 100 mods won't be helpful, because the maintainer will not know which mod is incompatible.\n
        Binary search is a way of finding the incompatible mod without removing the mods one-by-one. The procedure is simple:\n
        1. Backup the world because removing mod cause its content to be removed.\n
        2. Remove half of the existing mods, and put them aside.\n
        3. Run the game.\n
        4. Does the issue still exist?\n
        If YES: Repeat from step 2 with the current mods.\n
        If NO: Swap out the current mods with the ones set aside, and repeat from step 1.\n
        5. Repeat this process until the problematic mod(s) have been found.\n"
  - type: textarea
    id: link-to-incompat-mods
    attributes:
      label: Link to the incompatible mod
      description: "Provide the link to the related mods (can be Modrinth link, CurseForge link, GitHub link, etc.)" 
    validations:
      required: true
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Describe the issue. Drag the log and crash report to here. The log is `latest.log` in `logs` folder in the game directory. The log provides useful information (including the mod list) for debugging the issue.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### The maintainer may ask questions for clarifying this issue. Simply submitting a vague issue without replying will get ignored."
  - type: markdown
    attributes:
      value: "### Be polite to the maintainer. Impolite issues will be directly closed."
